### ISSUE TITLE
wrong version displayed for git dependencies in poetry 2

### ISSUE THREAD

**Issue by jorenham** [ninoseki/vscode-mogami#103]
### Describe the bug

Here, it incorrectly displays the version of `django` for the git dependencies, presumably because their names start with `django*`:

![Image](https://github.com/user-attachments/assets/24304ab6-2f72-4932-9a24-01e9fda58aa1)

but in reality, `django-cron` is at `0.6.0` and `django-suit` at `0.2.30`.

### Reproduction

in `pyproject.toml`:

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
[...]
dependencies = [
    "django ==5.1.6",
    "django-cron @ git+https://github.com/jorenham/django-cron.git@cec7465",
    "django-suit @ git+https://github.com/jorenham/django-suit.git@3d249e7",
]
```
