### ISSUE TITLE
codelens support for poetry 2 dev dependencies

### ISSUE THREAD

**Issue by jorenham** [ninoseki/vscode-mogami#104]
### Clear and concise description of the feature request

when `dependencies` are specified in a `poetry 2.0.1` project, there is no codelens for the poetry-style dev dependency definition 

![Image](https://github.com/user-attachments/assets/82ee58ca-8dae-4f5b-85c0-4ea30be4cd8b)

If I remember correctly, this used to work on `poetry <2`, when the runtime dependencies also had to be defined under `[tool.poetry]`.

### Additional context

in `pyproject.toml`

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
# ...
dependencies = ["django ==5.1.6"]

[tool.poetry.group.dev.dependencies]
django-stubs = "^5.1.2"
```
