### ISSUE TITLE
codelens displays (incorrect) versions for arbitrary strings

### ISSUE THREAD

**Issue by jorenham** [ninoseki/vscode-mogami#105]
### Describe the bug

If I define an arbitrary string in `pyproject.toml` that starts with the name of an installed package (at least with poetry 2, but I believe this also occurs with `uv`), codelens displays the version number of said package:

![Image](https://github.com/user-attachments/assets/9fe3e230-8bec-4c36-ab59-bf3f07332ad0)

### Reproduction

in `pyproject.toml`:

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
# ...
dependencies = ["django ==5.1.6"]

[tool.spam]
ham = ["djangoose_hunter_2000"]
```
