### ISSUE TITLE
Double-digit comparison issue

### ISSUE THREAD

**Issue by glass-ships** [ninoseki/vscode-mogami#122]
### Describe the bug

It looks like larger numbers with smaller _leading_ numbers introduce a false comparison. 
For example, `0.8.10` is showing as less than `0.8.9`, presumably because 1 is in fact less than 9, but it's not reading the full "10" before doing comparison

![Image](https://github.com/user-attachments/assets/57c56730-fb3a-4733-b005-c05a3792bb0e)

### Reproduction

Open a `.github/workflow/test.yml` with the following content, then enable Mogami:
```yaml
name: Test

on:
  workflow_dispatch:

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.10
```
