### ISSUE TITLE
Support uv's pyproject.toml

### ISSUE THREAD

**Issue by dekked** [ninoseki/vscode-mogami#82]
### Clear and concise description of the feature request

It would be nice to support uv's dependency format: https://docs.astral.sh/uv/concepts/dependencies/

It's basically PEP 508 so it mostly already works, except for dev dependencies are specified as:
```toml
[tool.uv]
dev-dependencies = [
  # ...
]
```
